name: Natanael's collection of thoughts
includes: ["_pages"]
permalink: /blog/:year-:month-:day-:title
category-list: [linux, crypto, security, math, protocols, software, miscellaneous]
page-type: [blog, notes] 
